// Generated by Wrangler by running `wrangler types --experimental-include-runtime=./runtime.d.ts --env-interface CloudflareBindings`

interface CloudflareBindings {
	kv: KVNamespace;
	DISCORD_APP_ID: string;
	DISCORD_GUILD_ID: string;
	DISCORD_CHANNEL_ID: string;
	DISCORD_TOKEN: string;
	DISCORD_PUBLIC_KEY: string;
	NOTION_DB_ID: string;
	NOTION_TOKEN: string;
}
