name: CI

on:
  push:
    branches: [ main ]
  pull_request:


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - run: corepack enable pnpm && pnpm i

      - run: pnpm test && pnpm lint
